stages:
  - build-dev
  - build-image-dev
  - deploy-dev

  - build-production
  - build-image-production
  - deploy-production


build-dev:
  stage: build-dev
  image: node:latest
  script:
    - npm cache clean --force
    - npm i --force
    - npm run build
    - mv dist build_front_dev
  rules:
    - if: $CI_PIPELINE_SOURCE != 'merge_request_event' && $CI_COMMIT_BRANCH == "dev"
  artifacts:
    paths:
      - build_front_dev
  tags:
    - stage-for-front-docker

build-image-dev:
  stage: build-image-dev
  script:
    - cp -r DockerfileDEV Dockerfile
    - docker login -u $CI_USERNAME -p $CI_PASSWORD registry.gitlab.com
    - docker build -t registry.gitlab.com/f3120/road-to-mountains-frontend:frontend$CI_COMMIT_SHA .
    - docker push registry.gitlab.com/f3120/road-to-mountains-frontend:frontend$CI_COMMIT_SHA
  rules:
    - if: $CI_PIPELINE_SOURCE != 'merge_request_event' && $CI_COMMIT_BRANCH == "dev"
  tags:
    - stage-for-front-shell

deploy-dev:
  stage: deploy-dev
  script:
    - docker login -u $CI_USERNAME -p $CI_PASSWORD registry.gitlab.com
#    - chgrp docker /usr/local/bin/docker-compose
#    - chmod 750 /usr/local/bin/docker-compose
    - docker-compose -f docker-compose-dev.yml up -d
  rules:
    - if: $CI_PIPELINE_SOURCE != 'merge_request_event' && $CI_COMMIT_BRANCH == "dev"
  tags:
    - stage-for-front-shell

build-production:
  stage: build-production
  image: node:latest
  script:
    - npm cache clean --force
    - npm i --force
    - npm run build
    - mv dist build_front_prod
  rules:
    - if: $CI_PIPELINE_SOURCE != 'merge_request_event' && $CI_COMMIT_BRANCH == "prod"
  artifacts:
    paths:
      - build_front_prod
  tags:
    - stage-for-front-docker

build-image-production:
  stage: build-image-production
  script:
    - cp -r DockerfilePROD Dockerfile
    - docker login -u $CI_USERNAME -p $CI_PASSWORD registry.gitlab.com
    - docker build -t registry.gitlab.com/f3120/road-to-mountains-frontend:prod$CI_COMMIT_SHA .
    - docker push registry.gitlab.com/f3120/road-to-mountains-frontend:prod$CI_COMMIT_SHA
  rules:
    - if: $CI_PIPELINE_SOURCE != 'merge_request_event' && $CI_COMMIT_BRANCH == "prod"
  tags:
    - stage-for-front-shell

deploy-production:
  stage: deploy-production
  script:
    - docker login -u $CI_USERNAME -p $CI_PASSWORD registry.gitlab.com
#    - chgrp docker /usr/local/bin/docker-compose
#    - chmod 750 /usr/local/bin/docker-compose
    - cp -r DockerfilePROD Dockerfile
    - docker-compose -f docker-compose-prod.yml up -d
  rules:
    - if: $CI_PIPELINE_SOURCE != 'merge_request_event' && $CI_COMMIT_BRANCH == "prod"
  tags:
    - stage-for-front-shell
