stages:
  - build-dev
  - build-image-dev
  - deploy-dev

build-dev:
  stage: build-dev
  image: node:latest
  script:
    - npm i --force
    - npm run build
    - mv build build_front_dev
  rules:
    - if: $CI_PIPELINE_SOURCE != 'merge_request_event' && $CI_COMMIT_BRANCH == "dev"
  artifacts:
    paths:
      - build_front_dev
  tags:
    - stage-for-docker

build-image-dev:
  stage: build-image-dev
  script:
    - docker login -u $CI_USERNAME -p $CI_PASSWORD registry.gitlab.com
    - cp Dockerfile Dockerfile
    # - echo -e 'FROM nginx:alpine\nEXPOSE 80\nCOPY /build /usr/share/nginx/html\nCMD ["nginx","-g","daemon off;"]' > Dockerfile
    - docker build -t registry.gitlab.com/f3120/road-to-mountains-frontend$CI_COMMIT_SHA .
    - docker push registry.gitlab.com/f3120/road-to-mountains-frontend$CI_COMMIT_SHA
  rules:
    - if: $CI_PIPELINE_SOURCE != 'merge_request_event' && $CI_COMMIT_BRANCH == "dev"
  tags:
    - stage-for-shell

deploy-dev:
  stage: deploy-dev
  script:
    - docker login -u $CI_USERNAME -p $CI_PASSWORD registry.gitlab.com
    - docker-compose up -d
  rules:
    - if: $CI_PIPELINE_SOURCE != 'merge_request_event' && $CI_COMMIT_BRANCH == "dev"
  tags:
    - stage-for-shell
